### ISSUE TITLE
Run ssh-key-action on Private container

### ISSUE THREAD

**Issue by kujaomega** [shimataro/ssh-key-action#165] opened 2021-01-19 17:04 UTC
First of all, thanks for the repo. It worked for me using a `runs-on: ubuntu-latest` but I have tested it with github actions using a private docker image and seems that it was not getting the right behaviour.
Using the action as follows in a private docker image as follows:

```
runs-on: ubuntu-latest
    container:
      image: gcr.io/api/image:latest
      credentials:
        username: _json_key
        password: ${{secrets.password}}
steps:
- name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.KEY }}
        name: id_rsa
        known_hosts: github.com
```
Wasn't getting access to the repositories I needed, and I found that known_hosts file was not well formatted and the ssh path was /github/home/.ssh  instead of /root/.ssh, as it seems the image needed.
To solve that, this commands made the trick:

```
ssh-keyscan github.com > /github/home/.ssh/known_hosts
cp -avr /github/home/.ssh /root/.ssh
```

**Comment by shimataro** [comment] 2021-02-07 12:34
Very sorry for late response.

I'm not familiar with GitHub Actions in private container; but according to [document](https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners), home directory is `/github/home` and user is `root`.

I probably should create files under `/root` when `HOME` is `/github/home`.
I have added it to my task list. Thanks!

- - -

> ```
> ssh-keyscan github.com > /github/home/.ssh/known_hosts
> ```

For security reason, you should use prefetched key instead of running `ssh-keyscan` per action.

```yaml
steps:
- name: Install SSH key
  uses: shimataro/ssh-key-action@v2
  with:
    key: ${{ secrets.KEY }}
    name: id_rsa
    known_hosts: |
      github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
```

**Comment by shimataro** [comment] 2021-02-08 14:35
@kujaomega 
Hi, I fixed it in #170.
Since I have not released new version yet, could you try to connect by using `shimataro/ssh-key-action@develop`?

```yaml
steps:
- name: Install SSH key
  uses: shimataro/ssh-key-action@develop # NOT "v2" BUT "develop"
  with:
    key: ${{ secrets.KEY }}
    name: id_rsa
    known_hosts: |
      github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
```

**Comment by till** [comment] 2021-02-24 11:01
@shimataro I can confirm that this works when I run _inside_ a container and use `@develop`. Exactly what I needed. :) Thanks very much!

**Comment by shimataro** [comment] 2021-03-02 11:28
[v2.2.0 released](https://github.com/shimataro/ssh-key-action/releases/tag/v2.2.0), closing this issue.
Please reopen it if the problem is not solved yet.

**Closed as completed by shimataro** 2021-03-02 11:28 UTC
